// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS5skIsVkVNqaGanM7hNKLjluT0LJDAVg',
    appId: '1:985410587906:web:0479e9e30e0e1d1fe3c61b',
    messagingSenderId: '985410587906',
    projectId: 'doctor-booking-app-6855',
    authDomain: 'doctor-booking-app-6855.firebaseapp.com',
    storageBucket: 'doctor-booking-app-6855.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhbHJSo5APDM7simJa2VLKf73LHHUrsy8',
    appId: '1:985410587906:android:083ea7ec24754d1ae3c61b',
    messagingSenderId: '985410587906',
    projectId: 'doctor-booking-app-6855',
    storageBucket: 'doctor-booking-app-6855.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAICtLoDcY1znc-D03L4nlI7Fmo6SE5b3Q',
    appId: '1:985410587906:ios:a3f2f68a77ae4902e3c61b',
    messagingSenderId: '985410587906',
    projectId: 'doctor-booking-app-6855',
    storageBucket: 'doctor-booking-app-6855.appspot.com',
    iosBundleId: 'com.example.doctorBookingFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAICtLoDcY1znc-D03L4nlI7Fmo6SE5b3Q',
    appId: '1:985410587906:ios:a3f2f68a77ae4902e3c61b',
    messagingSenderId: '985410587906',
    projectId: 'doctor-booking-app-6855',
    storageBucket: 'doctor-booking-app-6855.appspot.com',
    iosBundleId: 'com.example.doctorBookingFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS5skIsVkVNqaGanM7hNKLjluT0LJDAVg',
    appId: '1:985410587906:web:46e5b0ccb6275d95e3c61b',
    messagingSenderId: '985410587906',
    projectId: 'doctor-booking-app-6855',
    authDomain: 'doctor-booking-app-6855.firebaseapp.com',
    storageBucket: 'doctor-booking-app-6855.appspot.com',
  );
}
